import React from 'react';
import { Row, Col } from 'react-bootstrap';
import { IoMdPlay } from 'react-icons/io';

function AboutMeContainer() {
    return (
      <Row className='m-0'>
  <div className="item">
    <div id="timeline">
      <div>
        <section className="year">
          <h3 className="yearContainer">August 2019 to Present</h3>
          <section>
            <ul>
              <li>
                <h4>Altimetrik @ PayPal</h4>
                <h3 className="designation">Sr. Software Engineer</h3>
                <p className="experience">Reports generated by tableau server are integrated to web
application using tableau javascript API.Upgraded webpack version from 2 to 4 and by changing configuration,
 I have reduced application build time by 95%.Functionalities like Filter, Sorting and Result per page are
implemented.Dynamic
loading
implemented
to
improve
application
performance.</p>
              </li>
            </ul>
          </section>     
        </section>
        <section className="year">
          <h3 className="yearContainer">July 2018 to July 2019</h3>
          <section>
            <ul>
              <li>
                <h4>Streling Software Private Limited</h4>
                <h3 className="designation">Software Engineer</h3>
                <p className="experience">Coordinate with the Business team to define and implement the
requirements.Responsible for production deployment of the product in server.Developed a module called ‘Multitenancy’ which makes the
product to be used by more than one client.Implemented roles and privileges as a part of the product CER.Developed Common search module allows the user to search
term from any module which provides the related results of the
entire application.</p>
              </li>
            </ul>
          </section>     
        </section>
        <section className="year">
          <h3 className="yearContainer">October 2017 to June 2018</h3>
          <section>
            <ul>
              <li>
                <h4>Cavintek Software Private Limited</h4>
                <h3 className="designation">UI Designer and Developer</h3>
                <p className="experience">Collaborate with product management and engineering to define and implement innovative
solutions for the product direction, visuals and experience.Execute all visual design stages from concept to final hand-off to engineering.
Conceptualize original ideas that bring simplicity and user friendliness to complex design
roadblocks.Create wire frames, storyboards, user flows, process flows and site maps to effectively communicate
interaction and design ideas.</p>
              </li>
            </ul>
          </section>     
        </section>
        <section className="year">
          <h3 className="yearContainer">June 2016 to September 2017</h3>
          <section>
            <ul>
              <li>
                <h4>Dream Zone</h4>
                <h3 className="designation">Facilitator</h3>
                <p className="experience">Trained more than 20+ students in web designing including Photoshop, Illustrator, Flash, HTML, CSS,
Javascript, jQuery, etc.Provided face-to-face and web-based training for students.Designed and prepared course materials, teaching aids, skill evaluations, and final assessments.</p>
              </li>
            </ul>
          </section>     
        </section>
      </div>
    </div>
  </div>
      </Row>
    );
  }
  
  export default AboutMeContainer;